[tool.poetry]
name = "google_home"
version = "0.0.0"
description = "Home Assistant Google Home community integration"
authors = ["Ilja Leiko <leikoilja@gmail.com"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
glocaltokens = "0.3.0"
homeassistant = "^2021.3.4"
python = "^3.8"
zeroconf = "^0.29.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"
flake8-bugbear = "^21.4.3"
flake8-comprehensions = "^3.4.0"
flake8-simplify = "^0.14.0"
flake8-use-fstring = "^1.1"
homeassistant-stubs = "^2021.4.0b3"
isort = "^5.8.0"
mypy = "^0.812"
pre-commit = "^2.12.0"
pylint = "^2.7.4"
codespell = "^2.0.0"

[tool.pylint.messages_control]
# Reasons disabled:
# too-many-* - not enforced for the sake of readability
# too-few-* - same as too-many-*
disable = [
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-instance-attributes",
]

[tool.pylint.format]
max-line-length = 88

[tool.isort]
profile = "black"
force_sort_within_sections = true
combine_as_imports = true
known_first_party = [
    "homeassistant",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
